/**
 * Helper script to prepare project for deployment
 * This script ensures path aliases are handled correctly during deployment
 */
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import fs from 'fs';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, '..');

console.log('🚀 Preparing project for deployment...');

// Create a temporary .npmrc file to prevent treating @/ as an organization scope
const npmrcPath = resolve(rootDir, '.npmrc');
fs.writeFileSync(npmrcPath, `
# This file is generated by deploy-helper.js
# It prevents npm from interpreting @/ as an organization scope
save-exact=true
save-prefix=""
`);

console.log('✅ Project is ready for deployment!');
console.log('ℹ️ Note: For deployment, use node scripts/build.js to build the project');